--liquibase formatted sql
--changeset myname:create-multiple-tables splitStatements:true endDelimiter:;
CREATE TABLE easy_surveys.response(
	response_id			VARCHAR(64) 	NOT NULL,
	survey_id			VARCHAR(64) 	NOT NULL,
	owner_user_id		VARCHAR(64)	 	NOT NULL,
	created_dtm 		DATE	 		NOT NULL,
	submitted_dtm 		DATE	 		NULL,
	last_updated_dtm	DATE	 		NULL,
	CONSTRAINT pk_response_log	PRIMARY KEY (response_id)
);

CREATE TABLE easy_surveys.answer(
	answer_id			NUMBER(10) 		GENERATED BY DEFAULT AS IDENTITY,
	response_id			VARCHAR(64) 	NOT NULL,
	question_id			NUMBER(10)	 	NOT NULL,
	answer_value		VARCHAR2(255)	NULL,
	numeric_value		NUMBER(12, 2)	NULL,
	date_value			DATE			NULL,
	note				VARCHAR2(255)	NULL,
	changed_dtm			DATE	 		NOT NULL,
	CONSTRAINT pk_answer PRIMARY KEY (answer_id)
);

ALTER TABLE easy_surveys.answer ADD CONSTRAINT fk_answer_response_id
	FOREIGN KEY (response_id) REFERENCES easy_surveys.response(response_id);

-- Projections
CREATE TABLE easy_surveys.latest_answer(
	answer_id				NUMBER(10) 		NOT NULL,
	response_id				VARCHAR(64) 	NOT NULL,
	question_id				NUMBER(10)		NOT NULL,
	answer_value			VARCHAR2(255)	NULL,
	numeric_value			NUMBER(12, 2)	NULL,
	date_value				DATE			NULL,
	note					VARCHAR2(255)	NULL,
	changed_dtm				DATE	 		NOT NULL,
	CONSTRAINT pk_latest_answer	UNIQUE (response_id, question_id) DEFERRABLE INITIALLY DEFERRED
);

CREATE OR REPLACE VIEW easy_surveys.response_view AS
SELECT sr.response_id, survey_id, owner_user_id, created_dtm, submitted_dtm, answers_count, last_updated_dtm
 FROM easy_surveys.response sr
 JOIN (
	SELECT r.response_id, NVL(COUNT(a.response_id), 0) answers_count
	  FROM easy_surveys.response r
	  LEFT JOIN (
		SELECT la.response_id, la.changed_dtm, ROW_NUMBER() OVER (PARTITION BY la.response_id, la.question_id ORDER BY la.answer_id DESC) rn
		  FROM easy_surveys.latest_answer la
	)a ON a.response_id = r.response_id AND a.rn = 1
	GROUP BY r.response_id
 )x ON sr.response_id = x.response_id;


-- todo: Fks
GRANT INSERT, UPDATE, DELETE, SELECT ON easy_surveys.response TO easy_surveys_user;
GRANT INSERT, UPDATE, DELETE, SELECT ON easy_surveys.answer TO easy_surveys_user;
GRANT INSERT, UPDATE, DELETE, SELECT ON easy_surveys.latest_answer TO easy_surveys_user;
GRANT INSERT, UPDATE, DELETE, SELECT ON easy_surveys.response_view TO easy_surveys_user;
-- GRANT INSERT, UPDATE, DELETE, SELECT ON easy_survey_user.snapshot TO easy_survey_user;

-- GRANT INSERT, UPDATE, DELETE, SELECT ON easy_survey_user.latest_response_view TO easy_survey_user;
-- GRANT INSERT, UPDATE, DELETE, SELECT ON easy_survey_user.latest_answers_view TO easy_survey_user;
-- GRANT INSERT, UPDATE, DELETE, SELECT ON easy_survey_user.answers_snapshot_view TO easy_survey_user;
-- GRANT INSERT, UPDATE, DELETE, SELECT ON easy_survey_user.answers_snapshot_view TO easy_survey_user;

